# Generated by Django 5.2.8 on 2025-11-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('BANNER', 'Banner'), ('VIDEO', 'Video')], default='BANNER', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='ads')),
                ('video', models.FileField(blank=True, null=True, upload_to='ads')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('dislikes_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
