# Generated by Django 5.2.8 on 2025-11-10 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
