# Generated by Django 5.2.8 on 2025-11-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_alter_ad_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_render_type',
            field=models.CharField(choices=[('CUSTOM', 'Custom'), ('GOOGLE', 'Google')], default='CUSTOM', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='type',
            field=models.CharField(choices=[('BANNER', 'Banner'), ('VIDEO', 'Video'), ('CAROUSEL', 'Carousel')], default='BANNER', max_length=255),
        ),
    ]
