# Generated by Django 5.2.8 on 2025-11-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analytics_uid_alter_notification_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_video_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('SYSTEM', 'SYSTEM'), ('PROMO', 'PROMO')], default='SYSTEM', max_length=50),
        ),
    ]
