# Generated by Django 5.2.8 on 2025-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_category_uid_alter_comment_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_master_playlist',
            field=models.CharField(blank=True, help_text='Path to HLS master playlist (master.m3u8)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='hls_path',
            field=models.CharField(blank=True, help_text='Base directory path for HLS files', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/originals'),
        ),
    ]
