# Generated by Django 5.2.8 on 2025-12-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_ad_ad_render_type_alter_ad_description_alter_ad_name_and_more'),
        ('streaming', '0006_category_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='streaming.category'),
        ),
        migrations.AlterField(
            model_name='videoadslot',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_slots', to='advertising.ad'),
        ),
    ]
