# Generated by Django 5.2.8 on 2025-12-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_alter_video_category_alter_videoadslot_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoadslot',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='videoadslot',
            name='display_duration',
            field=models.PositiveIntegerField(default=5, help_text='Duration in seconds to display the ad (for images)'),
        ),
        migrations.AddField(
            model_name='videoadslot',
            name='media_file',
            field=models.FileField(blank=True, help_text='Image or video file for the interceptor ad', null=True, upload_to='interceptor_ads/'),
        ),
        migrations.AddField(
            model_name='videoadslot',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='videoadslot',
            name='redirect_link',
            field=models.URLField(blank=True, help_text='URL to redirect when ad is clicked', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videoadslot',
            name='end_time',
            field=models.TimeField(help_text='When the ad slot ends'),
        ),
        migrations.AlterField(
            model_name='videoadslot',
            name='start_time',
            field=models.TimeField(help_text='When the ad should appear during video playback'),
        ),
    ]
