# Generated by Django 5.2.8 on 2025-12-10 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_alter_videoadslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoadslot',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_slots', to='streaming.video'),
        ),
    ]
