# Generated by Django 5.2.8 on 2025-12-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_alter_videoadslot_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoadslot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoadslot',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
