# Generated by Django 5.2.8 on 2025-12-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_videoadslot_description_videoadslot_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoadslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
