# Generated by Django 5.2.8 on 2025-11-10 08:22

import apps.authentication.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(default=apps.authentication.models.Profile, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(default='USER', related_name='users', to='authentication.role'),
        ),
    ]
