# Generated by Django 5.2.8 on 2025-11-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_ad_ad_render_type_alter_ad_description_alter_ad_name_and_more'),
        ('authentication', '0006_otp'),
        ('streaming', '0004_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ads_clicked',
            field=models.ManyToManyField(blank=True, related_name='clicked_by', to='advertising.ad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ads_viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='advertising.ad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_videos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='streaming.video'),
        ),
        migrations.AddField(
            model_name='profile',
            name='videos_watched',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='streaming.video'),
        ),
    ]
