# Generated by Django 5.2.8 on 2025-11-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_ads_clicked_profile_ads_viewed_and_more'),
        ('streaming', '0005_playlist_playlistvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='downloaded_videos',
            field=models.ManyToManyField(blank=True, related_name='downloaded_by', to='streaming.video'),
        ),
    ]
