# Generated by Django 5.2.8 on 2025-11-29 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_profile_downloaded_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_os', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('app_version', models.CharField(max_length=255)),
                ('fcm_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.devices'),
        ),
    ]
